{"name": "test_raise_covid19_exception_should_pass", "status": "passed", "start": 1688253395363, "stop": 1688253395363, "uuid": "26696273-4380-4999-8752-5952e6bb16d7", "historyId": "5f99a8fc0c473ce304e6822ea32e2c6d", "testCaseId": "5f99a8fc0c473ce304e6822ea32e2c6d", "fullName": "api.coronavstech.companies.tests.test_api#test_raise_covid19_exception_should_pass", "labels": [{"name": "tag", "value": "django_db"}, {"name": "parentSuite", "value": "api.coronavstech.companies.tests"}, {"name": "suite", "value": "test_api"}, {"name": "host", "value": "fv-az449-126"}, {"name": "thread", "value": "2447-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "api.coronavstech.companies.tests.test_api"}]}