{"name": "test_should_be_ok_if_fails", "status": "skipped", "statusDetails": {"message": "XFAIL\n\nAssertionError: assert 1 == 2", "trace": "@pytest.mark.xfail\n    def test_should_be_ok_if_fails() -> None:\n>       assert 1 == 2\nE       assert 1 == 2\n\napi/coronavstech/companies/tests/test_api.py:76: AssertionError"}, "start": 1688253395292, "stop": 1688253395292, "uuid": "c3b32b80-d206-4598-96e1-59939978ed11", "historyId": "0132a9867b2f6ac79ebc0520c21b6126", "testCaseId": "0132a9867b2f6ac79ebc0520c21b6126", "fullName": "api.coronavstech.companies.tests.test_api#test_should_be_ok_if_fails", "labels": [{"name": "tag", "value": "@pytest.mark.xfail"}, {"name": "tag", "value": "django_db"}, {"name": "parentSuite", "value": "api.coronavstech.companies.tests"}, {"name": "suite", "value": "test_api"}, {"name": "host", "value": "fv-az449-126"}, {"name": "thread", "value": "2447-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "api.coronavstech.companies.tests.test_api"}]}